### ISSUE TITLE
Сохранение данных

### ISSUE THREAD

**Issue by nevermore077** [kl83/yii2-grid-sortable-column#1]
Добрый день, есть таблица "products" и в ней колонка "position" подскажите, пожалуйста action, как сохранять данные чтоб сразу после перетаскивания позиции сохранялась данные в столбец "position"!?

**Comment by kl83** [comment]
К сожалению какого-либо базового экшена для такого рода манипуляций тут нет. В этом репозитории есть только класс, который позволяет добавить колонку для перетаскивания строк в виджет DataGrid. При перетаскивании строки генерируется jQuery-событие. Дальше все нужно прописывать. Нужно написать экшен в котором будет меняться значение position. И нужно написать обработчик события 'sortablecolumn-sort' с обращением к этому экшену. В секции "Listen GridView event" README.md есть пример.

**Comment by nevermore077** [comment]
Спасибо, я решил уже данный вопрос, соединил ваше решение с другим и всё вышло как мне нужно!
